services:
  sshd:
    build: "."
    image: peterstory/sshd-password
    environment:
      - ROOT_PASSWORD
    ports:
      - "${LISTEN_SSHD}:22"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
